repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: pretty-format-json
        args: [--autofix, --no-ensure-ascii, --no-sort-keys]
      - id: check-ast
      - id: debug-statements
      - id: check-docstring-first

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: "isort (python)"
        types: [python]
        args:
        - "--profile=black"
      - id: isort
        name: "isort (pyi)"
        types: [pyi]
        args:
        - "--profile=black"
        - "--skip_gitignore"

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
        - --line-length=88
        - --include='\.pyi?$'
        - --exclude="""\.git* |
                    \.__pycache__|
                    \.mypy_cache"""

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        entry: flake8
        language: python
        types: [python]
        args:
        - "--max-line-length=88"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.930
    hooks:
      - id: mypy
        additional_dependencies:
          - types-dataclasses
          - types-requests

  # - repo: https://github.com/pycqa/pydocstyle
  #   rev: 6.1.1
  #   hooks:
  #   - id: pydocstyle
  #     exclude: "tests/"

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.1
    hooks:
      - id: bandit
        additional_dependencies: [toml]
        args: [--configfile, pyproject.toml, --recursive]
