[tool.poetry]
name = "pynblint"
version = "0.1.0"
description = "A linting library for Python Jupyter notebooks."
authors = ["Luigi Quaranta <luigi.quaranta@uniba.it>"]

[tool.poetry.dependencies]
python = "^3.7.10"
gitpython = {git = "https://github.com/gitpython-developers/GitPython"}
nbformat = "^5.1.3"
nbconvert = "^6.0.7"
ipython = "^7.24.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
